"""Emission: SymPy expressions -> pure TypeScript functions + guard metadata.

Per ADR-0001/0003: `sympy.printing.jscode` is the single executable-math
emitter (verified coverage incl. Piecewise/Abs/atan2/Min/Max; raises
PrintMethodNotImplementedError on unsupported constructs = loud failure).
Every emitted expression also yields auto-derived domain guards so removable
singularities surface as "undefined here" banners instead of NaN (invariant 5).
"""

from __future__ import annotations

import sympy as sp
from sympy.printing.jscode import jscode

from . import BuildError


def _params(exprs: list[sp.Expr]) -> list[str]:
    syms: set[str] = set()
    for e in exprs:
        syms |= {str(s) for s in e.free_symbols}
    return sorted(syms)


def check_powers(expr: sp.Expr, context: str) -> None:
    """JS Math.pow(negative, fractional) is NaN where SymPy may intend a real
    root. Reject fractional powers of possibly-negative bases at build time.
    (sqrt is allowed — it gets an auto nonneg guard instead.)
    """
    for p in expr.atoms(sp.Pow):
        exp = p.exp
        if exp.is_Integer:
            continue
        if exp == sp.Rational(1, 2) or exp == sp.Rational(-1, 2):
            continue  # printed as Math.sqrt; guarded separately
        if exp.is_number and not exp.is_Integer and p.base.is_nonnegative is not True:
            raise BuildError(
                f"{context}: fractional power {p} of a possibly-negative base — "
                f"declare the base positive, or rewrite via cbrt/sign"
            )


def emit_function(name: str, expr: sp.Expr, context: str, boolean: bool = False) -> str:
    """One entry of the generated `fns` record, CSE-compressed."""
    check_powers(expr, context)
    params = _params([expr])
    sig = f"({{ {', '.join(params)} }}: VarRecord)" if params else "(_: VarRecord)"
    try:
        if boolean or not expr.free_symbols:
            body = jscode(expr)
            return f"  {name}: {sig} => ({body}),"
        repl, red = sp.cse(expr, optimizations="basic")
        lines = [f"const {sym} = {jscode(sub)};" for sym, sub in repl]
        lines.append(f"return {jscode(red[0])};")
        body = " ".join(lines)
        return f"  {name}: {sig} => {{ {body} }},"
    except Exception as e:  # PrintMethodNotImplementedError and friends: fail loudly
        raise BuildError(f"{context}: cannot emit JS for {sp.srepr(expr)}: {e}") from e


def auto_guards(expr: sp.Expr, fn_prefix: str, target: str) -> list[tuple[str, sp.Expr, str, str]]:
    """(guard_fn_name, guard_expr, kind, message) for denominators and sqrt args.

    kind 'nonzero': runtime treats |value| < eps as undefined.
    kind 'nonneg':  runtime treats value < 0 as undefined.
    """
    guards: list[tuple[str, sp.Expr, str, str]] = []
    _, denom = sp.fraction(sp.together(expr))
    if denom.free_symbols:
        guards.append((
            f"{fn_prefix}__den",
            denom,
            "nonzero",
            f"{target} is undefined here (denominator {sp.sstr(denom)} = 0).",
        ))
    seen: set[sp.Expr] = set()
    for p in expr.atoms(sp.Pow):
        if p.exp in (sp.Rational(1, 2), sp.Rational(-1, 2)) and p.base.free_symbols:
            if p.base.is_nonnegative is True or p.base in seen:
                continue
            seen.add(p.base)
            guards.append((
                f"{fn_prefix}__sqrt{len(seen)}",
                p.base,
                "nonneg",
                f"{target} is undefined here (negative argument under a square root).",
            ))
    return guards


def render_fns_ts(entries: list[str], thing_id: str) -> str:
    joined = "\n".join(entries)
    return f"""// AUTO-GENERATED by mech_pipeline for '{thing_id}' — DO NOT EDIT.
// Every function was verified against the THING's relations at build time
// (tiered symbolic checker + high-precision numeric sampling). See docs/architecture.md.
export type VarRecord = Record<string, number>;

export const fns: Record<string, (v: VarRecord) => number | boolean> = {{
{joined}
}};
"""
